"""admin login lockout fields

Revision ID: db3e91025c47
Revises: b9af891f937d
Create Date: 2026-09-23 09:20:28.744515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3e91025c47'
down_revision: Union[str, Sequence[str], None] = 'b9af891f937d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='0' is required here (not just a Python-side
    # dataclass default) so this ALTER TABLE ADD COLUMN ... NOT NULL
    # succeeds against a table that already has rows - both SQLite and
    # PostgreSQL reject a NOT NULL column with no default on a
    # non-empty table otherwise. This is exactly the "existing
    # database -> upgrade -> latest schema" path (see
    # docs/PHASE2_TEST_PLAN.md-style migration tests).
    op.add_column('admin_users', sa.Column('failed_login_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('admin_users', sa.Column('locked_until', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'locked_until')
    op.drop_column('admin_users', 'failed_login_count')
    # ### end Alembic commands ###
